title: Introduction to Python
tagline: Step by step to your first Python application
description: Go from Hello World to writing a short random quote generator using Python.
template:
  name: python-random-quote
  repo: python-quotes
  description: "A file-based quote bot written in Python"
before:
  - type: createIssue
    title: Prepare your environment
    body: 01-environment.md

steps:
  - title: Set up your environment
    description: Check that Python and Git are installed
    event: issues.closed
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: respond
        with: 01-closed.md
        issue: 1
      - type: createIssue
        title: Run your first Python program
        body: 02-helloworld.md

tags:
  - Python
